# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-21 07:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_caption', models.CharField(blank=True, max_length=50, null=True)),
                ('txt_discription', models.TextField(blank=True, null=True)),
                ('jsn_images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dbl_tag1_weight', models.FloatField(blank=True, null=True)),
                ('dbl_tag2_weight', models.FloatField(blank=True, null=True)),
                ('dbl_tag3_weight', models.FloatField(blank=True, null=True)),
                ('dat_created', models.DateField(blank=True, null=True)),
                ('fk_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbl_total_tag1_weight', models.FloatField(blank=True, null=True)),
                ('dbl_total_tag2_weight', models.FloatField(blank=True, null=True)),
                ('dbl_total_tag3_weight', models.FloatField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_priority',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bln_review', models.BooleanField(default=False)),
                ('dat_review', models.DateField(blank=True, null=True)),
                ('fk_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post_app.TblPost')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_review',
                'managed': True,
            },
        ),
    ]
