# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20200721_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluserreview',
            name='int_dislike',
        ),
        migrations.RemoveField(
            model_name='tbluserreview',
            name='int_like',
        ),
        migrations.AddField(
            model_name='tbluserreview',
            name='bln_review',
            field=models.BooleanField(default=False),
        ),
    ]
